"""empty message

<<<<<<<< HEAD:migrations/versions/fe8a813971b6_.py
Revision ID: fe8a813971b6
Revises: 
Create Date: 2022-06-28 13:45:22.615628
========
Revision ID: 2e52513174bf
Revises: 
Create Date: 2022-06-28 13:52:41.125119
>>>>>>>> c8ec7a62f3a02d4c3f34257bc56f2d021518ed89:migrations/versions/2e52513174bf_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/fe8a813971b6_.py
revision = 'fe8a813971b6'
========
revision = '2e52513174bf'
>>>>>>>> c8ec7a62f3a02d4c3f34257bc56f2d021518ed89:migrations/versions/2e52513174bf_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board',
    sa.Column('board_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('board_id')
    )
    op.create_table('card',
    sa.Column('card_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['board.board_id'], ),
    sa.PrimaryKeyConstraint('card_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card')
    op.drop_table('board')
    # ### end Alembic commands ###
